---
- hosts: 192.168.1.68

  tasks:

  - name: add service data
    local_action:
      module: file
      path: debug.txt
      state: absent

  - name: add service data
    local_action:
      module: lineinfile
      path: debug.txt
      line: "<table> \n 2</table>"
      create: yes

  - name: add service data
    local_action:
      module: lineinfile
      path: debug.txt
      line: dadadadadadadaada

  - set_fact:
      test1: ''
  - set_fact:
      test1: "{{ test1 }}
      {{ item.line }}<td><td>"
    with_items:
      - { line: '111111111 <table>' }
      - { line: '2222222<table style="width:100%">' }
      - { line: '333333<tr><td width="500">adada service status</td> <td>444 for z minutes  </td>' }

  - debug:
      msg: "{{ test1 }}"
#  - name: add service data
#    local_action:
#      module: lineinfile
#      path: debug.txt
#      line: "{{ item.line }}"
#      regexp: '2<table>$'
#    with_items:
#      - { line: '<table>' }
#      - { line: 'xsxs <table>' }
#      - { line: 'xsxs<table style="width:100%">' }
#      - { line: '<tr><td width="500">adada service status</td> <td>444 for z minutes  </td>' }
#      - { line: '<tr><td width="500">cacaca service status</td> <td>f4 for xcxcx minutes</td>' }
#      - { line: 'xsxs</table>' }